// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TryitterAPI.Repository;

#nullable disable

namespace TryitterAPI.Migrations
{
    [DbContext(typeof(TryitterContext))]
    [Migration("20221214004714_CreateStudentAndPostTable")]
    partial class CreateStudentAndPostTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TryitterAPI.Models.Post", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Text")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UrlImage")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("StudentId")
                    .HasColumnType("int");

                b.HasKey("PostId");

                b.HasIndex("StudentId");

                b.ToTable("Posts");
            });

            modelBuilder.Entity("TryitterAPI.Models.Student", b =>
            {
                b.Property<int>("StudentId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("CurrentModule")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("nvarchar(10)");

                b.HasKey("StudentId");

                b.ToTable("Students");
            });

            modelBuilder.Entity("TryitterAPI.Models.Post", b =>
            {
                b.HasOne("TryitterAPI.Models.Student", "Student")
                    .WithMany("Posts")
                    .HasForeignKey("StudentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Student");
            });

            modelBuilder.Entity("TryitterAPI.Models.Student", b =>
            {
                b.Navigation("Posts");
            });
#pragma warning restore 612, 618
        }
    }
}
